on:
  push:
    branches: ['develop']

permissions:
  contents: read
  id-token: write

env:
  PRJID: "hosymo"
  PRJNU: "1064199407438"
  SA_NAME: "ghactions"
  PROVIDER_NAME: "oidc-gh"
  REPO_NAME: "priorit-ai"
  IMG: "backend"
  # RGN: "us-central1"
  RGN: "asia-northeast1"

jobs: 
  prod: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          PRJID: '$PRJID'
          workload_identity_provider: 'projects/$PRJNU/locations/global/workloadIdentityPools/$PROVIDER_NAME/providers/github'
          token_format: 'access_token'
          service_account: '$SA_NAME@$PRJID.iam.gserviceaccount.com'
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '$RGN-docker.pkg.dev'
      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: '.'
          push: true 
          tags: |
             $RGN-docker.pkg.dev/$PRJID/$REPO_NAME/$IMG:${{ github.sha }}
             $RGN-docker.pkg.dev/$PRJID/$REPO_NAME/$IMG:latest
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '$SERVICE_NAME'
          region: '$RGN'
          image: '$RGN-docker.pkg.dev/$PRJID/$REPO_NAME/$IMG:latest'
